name: Build iw7-mod

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run generate.bat
        shell: cmd
        run: |
          cd ${{ github.workspace }}
          call generate.bat

      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build solution
        shell: cmd
        run: |
          cd ${{ github.workspace }}/build
          msbuild.exe iw7-mod.sln /p:Configuration=Release /p:Platform=x64
