name: Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}}
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw7-mod.sln

      - name: Upload ${{matrix.configuration}} symbols
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{matrix.configuration}} Symbols
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.pdb
      - name: Upload ${{matrix.configuration}} binary
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{matrix.configuration}} Binary
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.exe
      - name: Upload ${{matrix.configuration}} data artifacts
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{matrix.configuration}} data artifacts
          path: |
            data/*
  create_release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download iw7-mod.exe
        uses: actions/download-artifact@v3
        with:
          name: Release
          path: artifacts

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          automatic_release_tag: v1.0.${{ github.run_number }}
          title: Release v1.0.${{ github.run_number }}
          prerelease: false
          files: |
            artifacts/iw7-mod.exe
